export const voucherConstants = {
    GET_VOUCHER_LOADING:    'GET_VOUCHER_LOADING',
    GET_VOUCHER_SUCCESS:    'GET_VOUCHER_SUCCESS',
    GET_VOUCHER_FAIL:       'GET_VOUCHER_FAIL',

    UPDATE_VOUCHER_UNITS:   'UPDATE_VOUCHER_UNITS',
}