export const DateFormat = {
    DateFormat: 'MMM DD YYYY',
    DateFormatCSharp: 'YYYYMMDD',
    DateFormatJson: 'YYYY-MM-DDT00:00:00',
    DateOnlyFormatJson: 'DD-MM-YYYY',
    DateFormatMMDDYYYY: 'MM/DD/YYYY',
    DateTimeFormat: 'MMM DD YYYY HH:mm',
    DateTimeFormatDDMMYYYYHHmm: 'DD-MM-YYYY HH:mm',
    DateTimeFormatJson: 'YYYY-MM-DDTHH:mm:ss',
    DateTimeFormatWithMeridiem: 'MMM DD YYYY HH:mm A',
    DayOfWeek: 'dddd',
    DayOfWeekShort: 'ddd',
    EndDayOfYear: 'YYYY-12-31T00:00:00',
    FullDate: 'MMM DD, YYYY HH:mm:ss',
    FullDay: 'DD',
    FullHour: 'HH',
    FullMinute: 'mm',
    FullMonth: 'MMMM',
    FullMonthYear: 'MMMM YYYY',
    FullYear: 'YYYY',
    MMDD: 'MM/DD',
    MinDateJson: '0001-01-01T00:00:00',
    MonthDay: 'MMM DD',
    ShortDayOfWeekWithMonthDay: 'ddd, MMM DD',
    ShortMonth: 'MMM',
    StartDayOfMonth: 'YYYY-MM-01T00:00:00',
    StartDayOfYear: 'YYYY-01-01T00:00:00',
    TimeFormat: 'HH:mm',
    TimeFormatHHMMSS: 'HH:MM:SS',
    TimeFormatHHMMTT: 'HH:MM tt'
};
